### ISSUE TITLE
Wrong order of creation models

### ISSUE THREAD

**Issue by pedro-stanaka** [developerdino/example-articles-api#4]
When you run artisan on your article to create the models you do the creation on the wrong order, causing a errors due to FK constraint creation. The order should be:

` People -> Articles -> Comments`

in the article you do:

`Articles -> People -> Comments`.

Thanks for the good article.

**Comment by developerdino** [comment]
Thanks for the info, I'll check it out and update the article once I confirm.

**Comment by AJDowds** [comment]
I ran into the same FK constraint error, followed the advice of @pedro-stanaka and the issue was resolved.

**Comment by developerdino** [comment]
This has now been updated in the article. Thanks for the feedback.
